/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type orderCreateErrors = {
    order?: {
        /**
         * Customer's unique identifier generated for this order request. This order number should be used for any future references.
         */
        orderNumber?: string;
        /**
         * The unique cartID generated for this order request. This cartId number is useful for troubleshooting errors during order creation.
         */
        cartId?: string;
        /**
         * Customer's checkout profile Id used to create the order. This is available in your myTI customer portal.
         */
        checkoutProfileId?: string;
        /**
         * Currency ISO code used for this order. For example for US order it will be USD.
         */
        currencyCode?: string;
        /**
         * The date when the order was created. Format for date is yyyy-MM-dd'T'HH:mm:ss'Z'.
         */
        orderDate?: string;
        /**
         * The channel through which this order was created. Possible values are API, EDI, TI.com, RPA.
         */
        orderEntry?: string;
        /**
         * Customer's purchase order number if available. This is an optional field.
         */
        customerPurchaseOrderNumber?: string;
        /**
         * Supplier status of order; possible values are Created, Submitted, Cancelled, In-Work, and Complete.
         */
        orderStatus?: string;
        /**
         * The name of the company that this order was placed by.
         */
        orderPlacedBy?: string;
        /**
         * Customer's end customer company name where these materials will be used. This information will be available if this was provided in your request.
         */
        endCustomerCompanyName?: string;
        /**
         * The name of the application where the materials in the order will be used. This information was provided in your checkout profile setup in myTI.
         */
        application?: string;
        /**
         * The name of the end equipment where the materials in the order will be used. This information was provided in your checkout profile setup in myTI.
         */
        endEquipment?: string;
        /**
         * Boolean flag of true or false as to whether the materials in the order will be used for any military end use. This was specified in your checkout profile setup in myTI.
         */
        intendedForMilitary?: boolean;
        /**
         * Boolean flag of true or false. If the order was created using the Test Order API end point, this will be false. If the order was created using the Production API, this will be set to true.
         */
        isProductionOrder?: boolean;
        totalOrderSummary?: {
            /**
             * Subtotal for the order.
             */
            subTotal?: number;
            /**
             * The amount of the discounts if applicable that were applied to this order.
             */
            estimatedDiscountAmount?: number;
            /**
             * The total shipping cost that was calculated for this order.
             */
            estimatedShippingCost?: number;
            /**
             * Additional inventory transfer fee (if applicable) to accommodate your order to ship from a United States location
             */
            estimatedInventoryTransferFee?: number;
            /**
             * The total estimated taxes that was calculated for this order.
             */
            estimatedTaxes?: number;
            /**
             * Total cost of the order after including the taxes, shipping costs and deducting any discounts or coupons.
             */
            orderTotal?: number;
        };
        discounts?: Array<{
            /**
             * Indicates the name of the discount that was applied. For example - custom reel discount.
             */
            type?: string;
            /**
             * Indicates the amount for the discount that was applied.
             */
            amount?: number;
        }>;
        lineItems?: Array<{
            /**
             * Line item number generated by Supplier.
             */
            tiLineItemNumber?: string;
            /**
             * Line item number supplied by Customer.
             */
            customerLineItemNumber?: string;
            /**
             * TI Part Number that was used for creating the order. You can find more details by visiting www.ti.com.
             */
            tiPartNumber?: string;
            /**
             * Customer provided Part Number.
             */
            customerPartNumber?: string;
            /**
             * The short description for this product. You can find more details by visiting ti.com, going to the specific product page for this part number and check the description section.
             */
            tiPartDescription?: string;
            /**
             * Indicates the part type whether this is an Integrated Circuit(IC) or EVM.
             */
            partType?: string;
            /**
             * Indicates if this part number has a harmonized tariff code.
             */
            htsCode?: string;
            /**
             * Indicates if this part number has certificate of conformance code.
             */
            cooCode?: string;
            /**
             * The requested quantity specified while placing the order.
             */
            quantity?: number;
            /**
             * The quantity that was shipped.
             */
            shippedQuantity?: number;
            /**
             * The Supplier unit price. You can find more details by visiting ti.com, going to the specific product page for this part number, and checking the pricing section.
             */
            unitPrice?: number;
            /**
             * The total net price of the product. This was calculated using unitPrice * quantity + fees(if any) - discounts offered(if any)
             */
            netPrice?: number;
            /**
             * Date code for Hirel parts
             */
            dateCode?: string;
            /**
             * Batch code if available.
             */
            batchCode?: string;
            /**
             * Indicates the status of the line item. Possible values are 'Submitted' or 'Shipped'. This status can be different from the full order status.
             */
            status?: string;
            fees?: Array<{
                /**
                 * Indicates type for the fees collected. For example - customer reel.
                 */
                type?: string;
                /**
                 * Indicates fees calculated for the service offered. For example there is fees for custom reel.
                 */
                amount?: number;
            }>;
            discounts?: Array<{
                /**
                 * Indicates name of the discount that was applied. For example - custom reel discount.
                 */
                type?: string;
                /**
                 * Indicates amount for the discount that was applied.
                 */
                amount?: number;
            }>;
            packageInformation?: {
                /**
                 * Indicates the package type used for example - Tape and Reel or Tube or Tray.
                 */
                carrier?: string;
                delivery?: Array<{
                    /**
                     * Indicates how packages are delivered whether it is cut-type, full reel, custom reel.
                     */
                    type?: string;
                    /**
                     * This indicates that quantity that package will be delivered. How many pieces are in cut-tape, full reel, custom reel.
                     */
                    quantity?: number;
                }>;
            };
            /**
             * If this part has waiver available it will be "true" else it will be 'false'.
             */
            waiverAvailable?: boolean;
            trackingAndShipping?: {
                trackingNumbers?: Array<{
                    /**
                     * Indicates if we are using TI shipping freight or customer freight account. The possible values are "TI" or "Customer".
                     */
                    shippingFreightAccount?: string;
                    /**
                     * The countrycode from where this product will be shipped from.
                     */
                    shippingFromCountryCode?: string;
                    /**
                     * The service level used by the shipping carrier provider. This could be "International Economy" or " Priority Shipping".
                     */
                    serviceLevel?: string;
                    /**
                     * This indicates the date when the items was shipped. Format for date is yyyy-MM-dd'T'HH:mm:ss'Z'.
                     */
                    shipDate?: string;
                    /**
                     * The master tracking number for this line item if available.
                     */
                    leg1masterTrackingNumber?: string;
                    /**
                     * The name of the carrier that is used to ship the product. Example -  "Fedex" or "DHL"
                     */
                    leg1Carrier?: string;
                    /**
                     * The tracking number that was provided by the shipping carrier.
                     */
                    leg1TrackingNumber?: string;
                    /**
                     * The tracking URL that was provided by the shipping carrier.
                     */
                    leg1TrackingUrl?: string;
                    /**
                     * The master tracking number for this line item if available.
                     */
                    leg2masterTrackingNumber?: string;
                    /**
                     * The name of the carrier that is used to ship the product for the scenario where we have another carrier that is doing the second leg of shipment for cross-border shipments. Example - "Fedex" or "DHL"
                     */
                    leg2Carrier?: string;
                    /**
                     * The tracking number that was provided by the shipping carrier for the scenario where we have another carrier that is doing the second leg of shipment for cross-border shipments.
                     */
                    leg2TrackingNumber?: string;
                    /**
                     * The tracking URL that was provided by the shipping carrier for the scenario where we have another carrier that is doing the second leg of shipment for cross-border shipments.
                     */
                    leg2TrackingUrl?: string;
                    /**
                     * The waybill number for the shipment. Use this number to retrieve any shipment notifications via the API.
                     */
                    waybillNumber?: string;
                }>;
                invoices?: Array<{
                    /**
                     * The type of invoice. This could be financial invoice or commercial invoice.
                     */
                    type?: string;
                    /**
                     * The invoice number that was generated. This number can be used for future reference.
                     */
                    number?: number;
                    /**
                     * If there are some special instructions the supplier has it will be mentioned here.
                     */
                    message?: string;
                }>;
                creditMemo?: {
                    /**
                     * Short description for the credit memo note available.
                     */
                    note?: string;
                    /**
                     * Date when the credit memo was created. Format for date is yyyy-MM-dd'T'HH:mm:ss'Z'.
                     */
                    date?: string;
                    /**
                     * Boolean value of true or false. If this is available it will true else it will be false.
                     */
                    multiShipFlag?: boolean;
                };
            };
            notifications?: Array<{
                /**
                 * The name of the category that this notification is applicable. For example - Shipping Method.
                 */
                topic?: string;
                /**
                 * Provides more details that is applicable to the order. For example if you shipping method option was not available, this notification will include the one what was used for shipping.
                 */
                detail?: string;
            }>;
            customerItemComments?: Array<{
                /**
                 * Customer pass-through text.
                 */
                message?: string;
            }>;
        }>;
        shippingAddress?: {
            /**
             * First name of the address.
             */
            firstName?: string;
            /**
             * Last name of the address.
             */
            lastName?: string;
            /**
             * Company name mentioned in the address.
             */
            company?: string;
            /**
             * Address line 1 of the address.
             */
            addressLine1?: string;
            /**
             * Address line 1 of the address.
             */
            addressLine2?: string;
            /**
             * Town or city of the address.
             */
            city?: string;
            /**
             * State or region of the address.
             */
            stateRegion?: string;
            /**
             * Postal code of the address.
             */
            postalCode?: string;
            /**
             * Two character ISO code of the country.
             */
            regionCode?: string;
            /**
             * Country name for the address.
             */
            region?: string;
            /**
             * Email address for the address.
             */
            email?: string;
            /**
             * Phone number for the address.
             */
            phoneNumber?: string;
            /**
             * URL specified for the address.
             */
            companyURL?: string;
        };
        billingAddress?: {
            /**
             * First name of the address.
             */
            firstName?: string;
            /**
             * Last name of the address.
             */
            lastName?: string;
            /**
             * Company name mentioned in the address.
             */
            company?: string;
            /**
             * Address line 1 of the address.
             */
            addressLine1?: string;
            /**
             * Address line 1 of the address.
             */
            addressLine2?: string;
            /**
             * Town or city of the address.
             */
            city?: string;
            /**
             * State or Region name of the address.
             */
            stateRegion?: string;
            /**
             * Postal code of the address.
             */
            postalCode?: string;
            /**
             * Two character ISO code of the country.
             */
            regionCode?: string;
            /**
             * Country name of the address.
             */
            region?: string;
            /**
             * Email address for the address.
             */
            email?: string;
            /**
             * Phone number for the address.
             */
            phoneNumber?: string;
            /**
             * URL specified for the address.
             */
            companyURL?: string;
        };
        payment?: {
            /**
             * Indicates the payment type used. This could be "TI Line of Credit" or "3rd Party Line of Credit" or 'Bank Tranfer'.
             */
            type?: string;
            /**
             * Indicates the payment method used. For example with '3rd Party Line of Credit' this would be 'Apruve'.
             */
            method?: string;
            /**
             * The email for bank transfer payment that require an admin email for order approval. This information was provided in the checkout profile ID setup.
             */
            bankTranferApproverEmail?: string;
            details?: {
                /**
                 * Company name to whom the wire is being sent.
                 */
                beneficiary?: string;
                /**
                 * An ABA number used for wires and electronic automatic clearing house (ACH) transactions such as electronic funds transfer.
                 */
                bankRoutingAndTransitNumber?: string;
                /**
                 * SWIFT (Society for Worldwide Interbank Financial Telecommunications) code is an 8-11 character long, standard format code that identifies banks and financial institutions worldwide.
                 */
                swiftCode?: string;
                /**
                 * Bank address of the beneficiary's bank that is going to receive the funds.
                 */
                bankAddress?: string;
                /**
                 * The account number in the beneficiary bank that is going to receive the funds. This account number would be specified in the pro-form invoice.
                 */
                accountNumber?: string;
                /**
                 * A correspondent bank is a financial institution authorized to provide services on behalf of another financial institution. This is an optional field.
                 */
                correspondentBankAccount?: string;
                /**
                 * The tax code if any that is assigned to the beneficiary. This is an optional field.
                 */
                beneficiaryTaxCode?: string;
                /**
                 * The tax registration code if any associated to the beneficiary. This is an optional field.
                 */
                beneficiaryTaxRegistrationCode?: string;
            };
        };
        taxInfo?: {
            /**
             * This is a boolean flag. If you had tax exemption certificate for this order then this value will be 'true' else it will be 'false'. This would have been specified in the check profile ID setup that was used for this order.
             */
            taxExemption?: boolean;
        };
        vatDetails?: Array<{
            /**
             * This indicates the type of VAT. Possible values are 'GST', 'PST' 'QST' for Canada. 'GST' for India. 'VAT' for China. This value could vary from country to country.
             */
            type?: string;
            detail?: {
                /**
                 * Indicates customer taxID number that has been associated to the company name registered with the government.
                 */
                customerTaxID?: string;
                /**
                 * Name of the company the taxID is associated.
                 */
                customerName?: string;
                /**
                 * The legal address of the company where the taxID is associated.
                 */
                registrationAddress?: string;
                /**
                 * The phone number of the company where the taxID is associated.
                 */
                contactPhone?: string;
                /**
                 * The mobile phone number of the company where the taxID is associated.
                 */
                contactMobilePhone?: string;
                /**
                 * The email address of the contact person in the company for any tax questions.
                 */
                contactEmail?: string;
                /**
                 * The name of the bank that has been registered with company for tax.
                 */
                bankName?: string;
                /**
                 * The bank account number of company that is registered with the bank name provided.
                 */
                bankAccountNumber?: string;
                salesOrderNo?: string;
                custAlternateName?: string;
                ceoName?: string;
                fapiaoType?: string;
                businessType?: string;
                customerType?: string;
                businessClassification?: string;
                gsnRegistrationAddress?: string;
                gsnRegistrationAddress2?: string;
                custcountryCode?: string;
                custcountryName?: string;
                contactName?: string;
                enabledFlag?: string;
                custDepositBankName?: string;
                custDepositBankNumber?: string;
                custDepositBankAccountNum?: string;
                relatedPartyFlag?: string;
                receiverName?: string;
                recevierCompany?: string;
                mailingMobile?: string;
                postCode?: string;
                emailAddress?: string;
                deliveryAddressProvince?: string;
                deliveryAddressCity?: string;
                deliveryAddressStreet?: string;
                createdDatetime?: string;
            };
        }>;
        orderComments?: Array<{
            /**
             * Customer pass-through text.
             */
            message?: string;
        }>;
        notifications?: Array<Record<string, any>>;
    };
    errors?: Array<{
        /**
         * Indicates the section where the error was noticed for example - shipping, billing, orderInfo, LineitemMessage.
         */
        section?: string;
        /**
         * Indicates the exact field where the error is related to within the section.
         */
        field?: string;
        /**
         * Indicates the type of error for example Validation error.
         */
        errorType?: string;
        /**
         * Indicates a error code that was assigned to trouble-shoot with TI support team.
         */
        errorCode?: string;
        /**
         * Indicates the reason for this error.
         */
        reason?: string;
        /**
         * Indicates message to the customer to take the appropriate action.
         */
        message?: string;
        data?: Array<{
            /**
             * Line item number supplied by Customer.
             */
            customerLineItemNumber?: string;
            /**
             * TI Part Number that was used for creating the order. You can find more details by visiting www.ti.com.
             */
            tiPartNumber?: string;
            /**
             * The requested quantity specified while placing the order.
             */
            quantity?: number;
            /**
             * The quantity that is available.
             */
            availableQuantity?: number;
            /**
             * The maximum order quantity for some low inventory parts.
             */
            limit?: string;
            /**
             * The number of days your company must wait before purchasing an order limited part again.
             */
            waitPeriod?: string;
        }>;
    }>;
};

